# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc1217a0c564c194fbff030608275e79d90bd0a27e4da4681b6b0b67e2eeea462afcce1945d2868116852b1f8e1ff2c67fe7266d01d6d32ed233afbbf4c9abe7

test:
  secret_key_base: 1c5fedf56bbb63e378761a6da768df9c74bfa00e89e6ae5aca34798cce46961641f50ddd99bff540342eb9e2e2e3fb66f1751095d5c218e9003597844444af0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
