# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51493c66f39a41452267afac1b869c86ee435e9ad27edbf1beb895c14edf3020cfe0dc1fa66eb32e2bbe6d2d7987580f4bfd6c5ea66fcca3d4c153e8ee51dd57

test:
  secret_key_base: 60839b42f25e8453608cbb669399242c834581f05c67b236104a90b9abdeba870f0f01a570eaf058133579d282d795582a2f9f17ac6bab9dd16e6f6fb729c8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
