# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5393f8f843ef2a16a42aa4c037f1e4dc7ad36b2e7d7d3fe17439e27d05798d8e91d11d7c75d9968dad2b105ed50d0c69bb3cee166a731f2efcbb0c9ee38f3514

test:
  secret_key_base: 9bb808acd13cbef945156389ae83d3741c55dbc71ff1d53eb556df8f43c0084300eaf1abcc612410f774f0b142fa280c04ee109942c4636d55fe1a35fba36fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
