# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41388b94317f5e5a01005c7d3d64b5b990f91a7d803bae58f77e2d718ca0a579efda139ad0fc15a19e7c555cfb6dc523735b246bf9588285ae7b530d74deb7f4

test:
  secret_key_base: b1e010fcad221d6b10c310234c4525d928e74524291857ed3954c21869ec1b6e7d382987d13fd2c9cc21a1b2bc10c9574573c6d8fba95c5552c9289dfdafb650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
