# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61253371a60c2e895b0f439a372de7175f88accf858b43c1f4638ae5fe1991d594fa2c7d6c5a13e385a96399f0386291b34a2f973d34f687f44480c07dc820a5

test:
  secret_key_base: 2fc9c95f86cd26ae15f34870dbfe4f4c65003347ef70c2e14074bf99f5c58f692a1aa6ad0ab8063eb2c33f09caad3cb1c06292ef29fe1e429100242d07c641d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
