# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 206cfaa3a4527cd8b8334b54067b684421c27bff2ff2aea7c74931b5b9ae5a6dcc273f41613ba7ea3ff936f7a687a2752d283805dde1b053781c3d33883f8a9a

test:
  secret_key_base: 8f140d5904111694e81f5ed653b608a691ae683718ece6bc46dc7f115858e5aa27e6fa7a9cd9ec635c2745032d9dfb43bb06e4e58e3d1236a4a7d1c4e5ffb5d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
